# Description: Front end deployment is not dockerised insted it directly copies build folder into  var/www/

name: Deploy to dev server school-app humming-bird-school.
on:
  push:
    branches:
      - humming-bird-school
jobs:
   deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_NAME_HUMMING_BIRD }}
          username: ${{ secrets.USERNAME_HUMMING_BIRD }}
          key: ${{ secrets.SSH_KEY_HUMMING_BIRD }}
          port: ${{ secrets.PORT_HUMMING_BIRD }}
          script: |    
               cd ${{ secrets.TARGET_DIR_HUMMING_BIRD }}
               ./deploy.sh
    -          
      name: Notify on Slack channel
      uses: iRoachie/slack-github-actions@v2.3.2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
      if: ${{ always() }}
