name: Deploy to gharwal-english-medium-school
on: 
  push: 
    branches:
      - gharwal-english-medium-school
jobs:
   deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: easingthemes/ssh-deploy@main
      with: 
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }} 
          script: | 
               cd ${{ secrets.TARGET_DIR }}
                chmod +x deploy.sh
               ./deploy.sh
