# Description: Front end deployment is not dockerised insted it directly copies build folder into var/www/
#Same file is used for deploying all schools and any number of domains 
name: Deploy to dev server school-app 
on:
  push:
    branches:
      - main 
jobs: 
   deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_NAME_PROD_JUN_7 }}
          username: ${{ secrets.USERNAME_PROD_JUN_7 }}
          key: ${{ secrets.SSH_KEY_PROD_JUN_7 }}
          port: ${{ secrets.PORT_PROD_JUN_7 }}
          script: |    
               cd ${{ secrets.TARGET_DIR_DEV }}
               ./deploy.sh
    -          
      name: Notify on Slack channel
      uses: iRoachie/slack-github-actions@v2.3.2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
      if: ${{ always() }}
