# Description: Front end deployment is not dockerised insted it directly copies build folder into var/www/

name: Deploy to dev server school-app
on:
  push:
    branches:
      - gharwal-english-medium-school
jobs:
   deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - 
      name: Deploy Stack
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_NAME_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          port: ${{ secrets.PORT_DEV }}
          script: |    
               cd ${{ secrets.TARGET_DIR_DEV }}
               ./deploy.sh
